// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwssddqsrjrbjlbakbdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3c3NkZHFzcmpyYmpsYmFrYmRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2MTU3NzAsImV4cCI6MjA1NDE5MTc3MH0.I8Xca9cTvR3aqhp9gFj6mUysLmfMf3INR_as5U5DFXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);